#!/usr/bin/env python3.4

import json
import datetime
import urllib.request
import shutil.copyfileobj
import os.path
#import sys

#import config file. api_key must be supplied!
#sys.path.append(os.getcwd())
import rainman_conf

#==================================================
# Fetching and importing the files using the cache

# number of rows in the plots (including 0)
plot_height_factor=2 #make this int in argparse and abs val it for error handling
plot_rows = 4+(plot_height_factor*4)

# save current time
current_time = int(datetime.datetime.now().strftime('%s'))

# lambda to querry for file modification time
file_modify_time = lambda file_name : os.path.getmtime(file_name) if os.path.isfile(file_name) else 0


# Download the weather from `url` and save it locally under `file_name`:
url="http://api.openweathermap.org/data/2.5/weather?lat="+str(rainman_conf.latitude)+"&lon="+str(rainman_conf.longitude)+"&APPID="+rainman_conf.api_key
# only download the file if the cached file is too old or dosent exist
if current_time - file_modify_time(rainman_conf.weather_file_name) > rainman_conf.cache_weather_expire:
    with urllib.request.urlopen(url) as response, open(rainman_conf.weather_file_name, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)
        
# Download the forecast from `url` and save it locally under `file_name`:
url="http://api.openweathermap.org/data/2.5/forecast?lat="+str(rainman_conf.latitude)+"&lon="+str(rainman_conf.longitude)+"&APPID="+rainman_conf.api_key
# only download the file if the cached file is too old or dosent exist
if current_time - file_modify_time(rainman_conf.forecast_file_name) > rainman_conf.cache_forecast_expire:
    with urllib.request.urlopen(url) as response, open(rainman_conf.forecast_file_name, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)


# load the current weather report
with open(rainman_conf.weather_file_name,'r') as weather_data_file:
    weather_data = json.load(weather_data_file)

# load the 5 day weather forecast
with open(rainman_conf.forecast_file_name,'r') as forecast_data_file:
    forecast_data = json.load(forecast_data_file)

#==================================================
# Unit conversions: lambda functions

# Temperature: Kelvin
farenheit = lambda K : float(format(int(K)*1.8 - 459.67, ".1f"))
celcius = lambda K : float(format(int(K) - 273.15, ".1f"))

# Pressure: hPa (hectopascals)

#==================================================
# save some data to lists
forecast_temp_data=[[forecast_data['list'][i]['dt'],farenheit(forecast_data['list'][i]['main']['temp'])] for i in range(len(forecast_data['list']))]
forecast_pressure_data=[[forecast_data['list'][i]['dt'],farenheit(forecast_data['list'][i]['main']['pressure'])] for i in range(len(forecast_data['list']))]

#==================================================

def print_row_data(gps,row_num):
# function which decides when to print "*" in the ascii plot
    col_number=len(gps)
    
    for col in range(col_number-1):

        if row_num == gps[col]:
            print("*",end="")
        elif gps[col]<row_num and gps[col+1]>row_num:
            print("*",end="")
        elif gps[col]>row_num and gps[col+1]<row_num:
            print("*",end="")
        else:
            print(" ",end="")

def date_axis_label(utf):
    # print the bottom axis label. takes the starting utf date as func argument
    date_string="|  Sun  |  Mon  |  Tue  |  Wed  |  Thu  |  Fri  |  Sat  |  Sun  |  Mon  |  Tue  |  Wed  |  Thu  |  Fri  |  Sat  |"
    date_string_staring_index = int(( int(datetime.datetime.fromtimestamp(int(utf)).strftime('%w'))*24 \
            + int(datetime.datetime.fromtimestamp(int(utf)).strftime('%H'))-1 )\
            /3)
    return date_string[date_string_staring_index:date_string_staring_index+38]

def forecast_ascii_plot(data_list,data_name):
    
    max_data=max([row[1] for row in data_list])
    min_data=min([row[1] for row in data_list])
    
    #labels for y-axis
    mid_high_label=(max_data-min_data)*.75 + min_data
    mid_label=(max_data-min_data)*.5 + min_data
    mid_low_label=(max_data-min_data)*.25 + min_data
    
    # spaces to pad the left with
    left_pad_spaces=8
    
    #lambda function for printing the y-axes label numbers
    label_print = lambda value,spaces : print(format(value, ".1f").rjust(spaces)+"|",end="")
    
    # calculate which rows get a plot symbol
    gps=[ abs(int((data_list[i][1]-min_data)/(max_data-min_data)*plot_rows)-plot_rows) for i in range(len(data_list)) ]
    
    # Plot title (given from data_name)
    print(left_pad_spaces*" " + int(1 + max(0,((38-len(data_name))/2.)))*" " + data_name)
    
    # first row (top of the plot)
    print(left_pad_spaces*" "+" _______________________________________")
    
    for rows in range(plot_rows+1):
        if rows == 0:
            label_print(max_data,left_pad_spaces)
        elif rows == (plot_height_factor+1)*1:
            label_print(mid_high_label,left_pad_spaces)
        elif rows == (plot_height_factor+1)*2:
            label_print(mid_label,left_pad_spaces)
        elif rows == (plot_height_factor+1)*3:
            label_print(mid_low_label,left_pad_spaces)
        elif rows == (plot_height_factor+1)*4:
            label_print(min_data,left_pad_spaces)
        else:
            print(left_pad_spaces*" "+"|",end="")
        print_row_data(gps,rows)
        print("|")
        
    # bottom row (bottom of the plot)
    print(left_pad_spaces*" "+"|_______________________________________|")
    
    # date axis labels
    print(left_pad_spaces*" "+" "+date_axis_label(data_list[0][0]))

#==================================================

forecast_ascii_plot(forecast_temp_data,"Temperature (Farenheit)")

forecast_ascii_plot(forecast_pressure_data,"Pressure (hPa)")
